# Generated by Django 5.0.3 on 2024-03-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id_aposta', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('cpf', models.CharField(max_length=14)),
                ('numero_1', models.IntegerField()),
                ('numero_2', models.IntegerField()),
                ('numero_3', models.IntegerField()),
                ('numero_4', models.IntegerField()),
                ('numero_5', models.IntegerField()),
                ('valor_premio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Premio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('premio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id_sorteio', models.AutoField(primary_key=True, serialize=False)),
                ('numero_sorteado', models.TextField(max_length=550)),
                ('ganhador', models.TextField()),
                ('rodadas', models.TextField()),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
